### ISSUE TITLE
소스코드 디렉토리 생성

### ISSUE THREAD

**Issue by 112jshjshold** [112jshjsh/SWP1#2]
[문제점] 소스코드와 다른 파일들이 섞여 있음 → 분리하여 관리하기 어려움.

[개선 방안] src 부 디렉토리를 생성, 소스 코드를 src 디렉토리로 이동하여 다른 파일들과 분리

**Comment by 112jshjsh** [comment]
Done.

**Comment by 112jshjshold** [comment]
Done.
